"""Added review enhancements

Revision ID: 08d7643e8964
Revises: 758985a106ce
Create Date: 2026-05-23 13:59:20.786615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d7643e8964'
down_revision = '758985a106ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_amenities_name'), ['name'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('helpful_count', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_parent_id_reviews'), 'reviews', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_parent_id_reviews'), type_='foreignkey')
        batch_op.drop_column('helpful_count')
        batch_op.drop_column('is_edited')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_amenities_name'), type_='unique')

    # ### end Alembic commands ###
